[failure-bot] Test for commit message

diff --git a/.github/workflows/ci_exp.yml b/.github/workflows/ci_exp.yml
--- a/.github/workflows/ci_exp.yml
+++ b/.github/workflows/ci_exp.yml
@@ -17,6 +17,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
+      - name: Simulate OpenWISP checkcommit failure
+        run: |
+          echo "ERROR: checkcommit failed: No capital letter after prefix. Message: '[qa] updated python script.'"
+          exit 1
       
       - name: Set up Python
         uses: actions/setup-python@v5
